[workspace]
resolver = "2"
members = [
    "cassie_common",
    "cassie_cache",
    "cassie_config",
    "cassie_domain",
    "cassie_orm",
    "cassie_storage",
    "cassie_web",
    "cassie_casbin_adapter",
    "cassie_tests"
]

