[workspace]
members = [
    "cassie_common",
    "cassie_config",
    "cassie_domain",
    "cassie_orm",
    "cassie_rules",
    "cassie_upload",
    "cassie_web",
    "cassie_casbin_adapter",
    "cassie_tests"
]

