[workspace]
resolver = "2"
members = [
    "cassie_common",
    "cassie_config",
    "cassie_domain",
    "cassie_devtools",
    "cassie_orm",
    "cassie_storage",
    "cassie_web",
    "cassie_wx",
    "cassie_casbin_adapter",
    "cassie_tests"
]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false



[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false