[package]
name = "cassie_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autowired="0.1"
autowired-derive = "0.1.8"